### ISSUE TITLE
Plugin does not find jquery for datatables in Hogfather

### ISSUE THREAD

**Issue by bjquast** [giterlizzi/dokuwiki-plugin-datatables#50]
After upgrading to DW-version "Hogfather" the plugin does not find jquery for the datatables js library any more.

**Comment by giterlizzi** [comment]
Hi,
please add a screen of JS error console.

Thanks,
Joseph

**Comment by bjquast** [comment]
Sorry, I forgot to mention, I used the DokuWiki Upgrade Plugin of Andreas Gohr to upgrade the wiki from Greebo to Hogfather.

Do these screenshots help you?
![log1_](https://user-images.githubusercontent.com/15418064/83531193-ef2a8600-a4ec-11ea-8438-7e7e581dd9f2.jpg)
![log2_](https://user-images.githubusercontent.com/15418064/83531276-0a959100-a4ed-11ea-9406-597770cdd725.jpg)

Björn

**Comment by giterlizzi** [comment]
Hi,
Hogfather now use the "defer" attribute for speedup the JS loading but this attribute break some plugins.
You can temporary disable the defer attribute using ``defer_js`` option in Configuration Manager (see https://www.dokuwiki.org/config:defer_js).

I'm working to release a new version of plugin with an updated version of DataTables and a fix for this issue without a workaround.

**Comment by bjquast** [comment]
Hi,
disabling the defer-attribute fixes the problem for me. Thanks! 
I close the issue
Björn
