### ISSUE TITLE
possible typo in action.php file

### ISSUE THREAD

**Issue by BrommD** [giterlizzi/dokuwiki-plugin-datatables#71]
is this supposed to be correct?
![image](https://github.com/giterlizzi/dokuwiki-plugin-datatables/assets/33422643/90d7469b-e1fb-4df5-ba0b-2346fb4cbc3f)

this issues
`NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function sexplode() in /app/lib/plugins/datatables/action.php:133`

removing the `s` at least removes the error...
thx, Dejan

**Comment by giterlizzi** [comment]
Fixed and updated the plugin version in DokuWiki.org
Thanks! ;)

**Comment by saggi-dw** [comment]
Hi, this is a new function in DokuWiki, not a typo: https://github.com/dokuwiki/dokuwiki/pull/3754

**Comment by BrommD** [comment]
hi

this means, Dokuwiki should be updated to newest version before applying this plugin update? What about PHP? PHP8 required, too?

thx

**Comment by saggi-dw** [comment]
> this means, Dokuwiki should be updated to newest version before applying this plugin update?

Not at the moment, the change has been reverted (https://github.com/giterlizzi/dokuwiki-plugin-datatables/commit/7e3e0bfcaf746dc4755a1ed19f79fbb4bb9cc91c). I just wanted to let you know that the new DokuWiki release includes this function.
